# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtunnel < Formula
  desc ""
  homepage "https://github.com/manoj-inukolunu/homebrew-tools"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.2.1/jtunnel-go_Darwin_arm64.tar.gz"
      sha256 "76bb0ea64004d8c5fd3cd261c6f977339f47b231b8f0732ac374929952188ed2"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.2.1/jtunnel-go_Darwin_x86_64.tar.gz"
      sha256 "5562321af26e801ff370a5898a28f17d015066ed055eb69b279285544d9c2190"

      def install
        bin.install "jtunnel-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.2.1/jtunnel-go_Linux_arm64.tar.gz"
      sha256 "cb7e103916877102819194a683c8a75fb58b57cb7df17f854f760158a4b41ed4"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.2.1/jtunnel-go_Linux_x86_64.tar.gz"
      sha256 "c636e75944e116a0cab57a883b9211e2edcb64f99926ce37c4c4f132d9995a5d"

      def install
        bin.install "jtunnel-go"
      end
    end
  end
end
