# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtunnel < Formula
  desc ""
  homepage "https://github.com/manoj-inukolunu/homebrew-tools"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.7/jtunnel-go_Darwin_arm64.tar.gz"
      sha256 "bf482bef66044352a9fbb90bd78c40ba0ba61c2bfc6111d2af8f970183951c5d"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.7/jtunnel-go_Darwin_x86_64.tar.gz"
      sha256 "1d56e6efc88f799dcf985bb390ca1d6c34167485b4ac14d1b25004b85a76ec96"

      def install
        bin.install "jtunnel-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.7/jtunnel-go_Linux_arm64.tar.gz"
      sha256 "6d2b3c919a5c4bc132cd798848fe0b09ede8b0a991912465146ecb93af03d74c"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.7/jtunnel-go_Linux_x86_64.tar.gz"
      sha256 "c21d7fa3bcc63ecd1c90346c5ebae8e07254f966bef8dc9f104bfc9ad9701433"

      def install
        bin.install "jtunnel-go"
      end
    end
  end
end
