# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtunnel < Formula
  desc ""
  homepage "https://github.com/manoj-inukolunu/homebrew-tools"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.3/jtunnel-go_Darwin_arm64.tar.gz"
      sha256 "1df4f59fbbad88f072a2661684be60c573b4d2a61b2dd57e9b2f3ee17db5ef1e"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.3/jtunnel-go_Darwin_x86_64.tar.gz"
      sha256 "de190d427395eea2248f224bb3aba0bbb5a8aee416364eb6942e80776e436ac8"

      def install
        bin.install "jtunnel-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.3/jtunnel-go_Linux_arm64.tar.gz"
      sha256 "87c069a3f679a7e2d37e811980ce92c7002cbe9417b51f6ac30008a7a0020821"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.1.3/jtunnel-go_Linux_x86_64.tar.gz"
      sha256 "b045f4f1a5b45d51648db351c0a9c1eafcb16f8aadf011449be737ca7cff60c1"

      def install
        bin.install "jtunnel-go"
      end
    end
  end
end
