# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Migtunnel < Formula
  desc "Tunneling tool like ngrok and localtunnel"
  homepage "https://github.com/manoj-inukolunu/homebrew-tools"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/migtunnel/releases/download/v0.2.7/migtunnel_Darwin_arm64.tar.gz"
      sha256 "3cfe4c4381986b23cca29383eaa0828499e5eddd687fb02487514ed39788a64f"

      def install
        bin.install "migtunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/migtunnel/releases/download/v0.2.7/migtunnel_Darwin_x86_64.tar.gz"
      sha256 "6caf985222101934fc619efb102600854134f036b7c2361da29d67ff5c34fe61"

      def install
        bin.install "migtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/migtunnel/releases/download/v0.2.7/migtunnel_Linux_arm64.tar.gz"
      sha256 "46a6e24c9660915f77c1fa7aeb3373707efa7a8c4e0011e801bf012d2213b2df"

      def install
        bin.install "migtunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/migtunnel/releases/download/v0.2.7/migtunnel_Linux_x86_64.tar.gz"
      sha256 "e6bf7e96278136d9608e436e0c2cc71846307c70f67d90083cc4973ef8da3bfa"

      def install
        bin.install "migtunnel"
      end
    end
  end
end
